In [1]:
"This is Python code"

'This is Python code'

In [3]:
!which python

/opt/miniconda3/envs/eventGlyth/bin/python


In [4]:
#string 
print("this is some text")
#numbers
print(1234)

this is some text
1234


In [5]:
import torch 
x = torch.rand(5, 3)
print(x)

tensor([[0.4128, 0.5097, 0.2202],
        [0.0243, 0.6473, 0.0975],
        [0.3317, 0.5424, 0.8541],
        [0.7506, 0.2683, 0.8649],
        [0.0482, 0.2309, 0.9814]])


In [6]:
device = "cpu"

if torch.cuda.is_available():
    device = "cuda"

elif torch.backends.mps.is_available():
    device = "mps"

print(f"Using {device} device")

Using mps device


In [10]:
print("1 + 2 = ")
print(1 + 2)

1 + 2 = 
3


In [12]:
print ("hello" + " world")

hello world


In [13]:
a = 6
b = 4

print ( a + b)

10


In [14]:
# Declare x
x = 5

In [15]:
print (x)

5


In [19]:
# Let's call this "Cell A"
x = x + 1

In [20]:
# Let's call this "Cell B"
print (x)

8


In [21]:
import torch
torch.__version__

'2.10.0'

In [23]:
# Scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [24]:
scalar.ndim

0

In [25]:
# Get the Python number within a tensor (ony works with one-element tensors)
scalar.item()

7

In [27]:
# Vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [28]:
vector.ndim

1

In [29]:
# CHeck shape of vector
vector.shape

torch.Size([2])

In [30]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [31]:
MATRIX.ndim

2

In [32]:
MATRIX.shape

torch.Size([2, 2])

In [34]:
tense = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tense

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [35]:
tense.ndim

3

In [36]:
tense.shape

torch.Size([1, 3, 3])

In [37]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1160, 0.8544, 0.4071, 0.3502],
         [0.3863, 0.6156, 0.6641, 0.5576],
         [0.1784, 0.8935, 0.8331, 0.4863]]),
 torch.float32)

In [38]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [39]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [40]:
ones = torch.ones (size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [41]:
zero_to_ten_depreciated = torch.range(0, 10)

#create a range of valies 0 to 10
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

/var/folders/4f/kc52jy0j5vnb8jxkfv4mvppc0000gn/T/ipykernel_46690/3468992802.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_depreciated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
import sys
print(sys.version)

3.12.12 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 20:07:49) [Clang 20.1.8 ]


In [43]:
!pip install pytesseract

  Using cached pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Using cached pytesseract-0.3.13-py3-none-any.whl (14 kB)


In [44]:
import cv2
import numpy as np
from pathlib import Path

img = cv2.imread("sourcebook/pages/page_054.png")
print("Image shape:", img.shape)

# Check the grid cell boundaries it's calculating
h, w = img.shape[:2]
margin = 15
cell_w = (w - 2 * margin) // 6
cell_h = (h - 2 * margin) // 7

print(f"Page size: {w}w x {h}h")
print(f"Cell size: {cell_w}w x {cell_h}h")

# Check if the first few cells have any ink
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

for row in range(3):
    for col in range(3):
        x1 = margin + col * cell_w
        y1 = margin + row * cell_h
        x2 = x1 + cell_w
        y2 = y1 + cell_h
        cell = thresh[y1:y2, x1:x2]
        inv = 255 - cell
        print(f"Cell ({row},{col}) — ink sum: {inv.sum()}")

Image shape: (3830, 2800, 3)
Page size: 2800w x 3830h
Cell size: 461w x 542h
Cell (0,0) — ink sum: 8832180
Cell (0,1) — ink sum: 17536350
Cell (0,2) — ink sum: 4927875
Cell (1,0) — ink sum: 5643150
Cell (1,1) — ink sum: 7225935
Cell (1,2) — ink sum: 7071405
Cell (2,0) — ink sum: 7293000
Cell (2,1) — ink sum: 6092460
Cell (2,2) — ink sum: 9657870


In [45]:
import cv2
import numpy as np
from pathlib import Path

# ── config ──────────────────────────
image_path = Path("sourcebook/pages/page_054.png")
output_dir = Path("sourcebook/dataset")
output_dir.mkdir(parents=True, exist_ok=True)

COLS         = 6
ROWS         = 7
SYMBOL_RATIO = 0.72
margin       = 15

# ── load ─────────────────────────────
img  = cv2.imread(str(image_path))
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(f"Loaded: {img.shape}")

# ── compute grid ─────────────────────
h, w  = img.shape[:2]
cell_w = (w - 2 * margin) // COLS
cell_h = (h - 2 * margin) // ROWS
print(f"Cell size: {cell_w} x {cell_h}")

# ── draw grid preview ─────────────────
preview = img.copy()

for row in range(ROWS):
    for col in range(COLS):
        x1 = margin + col * cell_w
        y1 = margin + row * cell_h
        x2 = x1 + cell_w
        y2 = y1 + cell_h
        split_y = y1 + int(cell_h * SYMBOL_RATIO)

        # green = cell border, orange = symbol/label split
        cv2.rectangle(preview, (x1, y1), (x2, y2), (0, 180, 90), 2)
        cv2.line(preview, (x1, split_y), (x2, split_y), (0, 140, 255), 2)

# ── save ─────────────────────────────
out_path = output_dir / "page_054_preview.png"
result   = cv2.imwrite(str(out_path), preview)
print(f"imwrite returned: {result}")
print(f"Preview saved to: {out_path.resolve()}")
print(f"File exists: {out_path.exists()}")

Loaded: (3830, 2800, 3)
Cell size: 461 x 542
imwrite returned: True
Preview saved to: /Users/evanderduncan/Desktop/2026 Projects/Event-Glyph/sourcebook/dataset/page_054_preview.png
File exists: True


In [51]:
import cv2
import numpy as np
from pathlib import Path

image_path = Path("sourcebook/pages/page_054.png")
output_dir = Path("sourcebook/dataset")
output_dir.mkdir(parents=True, exist_ok=True)

img  = cv2.imread(str(image_path))
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
h, w = img.shape[:2]
print(f"Image: {w}w x {h}h")

COLS         = 6
ROWS         = 7
# Manually measured margins to align with the printed cell borders
top_margin    = 210   # below the ASTRONOMY header
bottom_margin = 410   # above the footnote and page number
left_margin   = 70
right_margin  = 80

usable_w = w - left_margin - right_margin
usable_h = h - top_margin - bottom_margin
cell_w   = usable_w // COLS
cell_h   = usable_h // ROWS

SYMBOL_RATIO = 0.75   # push split line lower — more of cell is symbol

print(f"Usable area: {usable_w}w x {usable_h}h")
print(f"Cell size:   {cell_w}w x {cell_h}h")

preview = img.copy()

for row in range(ROWS):
    for col in range(COLS):
        x1 = left_margin  + col * cell_w
        y1 = top_margin   + row * cell_h
        x2 = x1 + cell_w
        y2 = y1 + cell_h
        split_y = y1 + int(cell_h * SYMBOL_RATIO)

        cv2.rectangle(preview, (x1, y1), (x2, y2), (0, 180, 90), 3)
        cv2.line(preview, (x1, split_y), (x2, split_y), (0, 140, 255), 2)

out_path = output_dir / "page_054_preview_v7.png"
cv2.imwrite(str(out_path), preview)
print(f"Saved: {out_path.resolve()}")

Image: 2800w x 3830h
Usable area: 2650w x 3210h
Cell size:   441w x 458h
Saved: /Users/evanderduncan/Desktop/2026 Projects/Event-Glyph/sourcebook/dataset/page_054_preview_v7.png


In [54]:
import cv2
import numpy as np
from pathlib import Path

def find_all_grid_lines(gray, line_width_threshold=0.55, min_gap=50):
    h, w = gray.shape
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
    inv = 255 - binary

    lines = []
    last_line_y = -min_gap

    for y in range(0, h):
        row_sum = inv[y, :].sum()
        if row_sum > (line_width_threshold * w * 255):
            if y - last_line_y > min_gap:
                lines.append(y)
                last_line_y = y

    return lines


def find_grid_extent(gray):
    lines = find_all_grid_lines(gray)

    if len(lines) < 2:
        print("  Warning: fewer than 2 grid lines found, using fallback margins")
        h = gray.shape[0]
        return 210, h - 410

    grid_top    = lines[0]
    grid_bottom = lines[-1]

    print(f"  Found {len(lines)} border lines")
    print(f"  Grid extent: y={grid_top} to y={grid_bottom}")

    return grid_top, grid_bottom

In [56]:
import cv2
from pathlib import Path

# Test on a range of known awkward pages
test_pages = [
    "page_054.png",  # clean full grid
    "page_038.png",  # likely has overflow from previous section
    "page_080.png",  # likely has intro paragraph at bottom
    "page_120.png",  # another section transition
]

for page in test_pages:
    img  = cv2.imread(f"sourcebook/pages/{page}")
    if img is None:
        print(f"{page} — not found, skipping")
        continue
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    lines = find_all_grid_lines(gray)
    top, bottom = find_grid_extent(gray)
    print(f"\n{page}")
    print(f"  All lines at: {lines}")
    print(f"  Using grid: {top} → {bottom}")

    # Save a preview for each
    preview = img.copy()
    h, w = img.shape[:2]
    cv2.line(preview, (0, top),    (w, top),    (0, 200, 80),  3)
    cv2.line(preview, (0, bottom), (w, bottom), (0, 100, 255), 3)
    cv2.imwrite(f"sourcebook/dataset/{page.replace('.png','')}_extent.png", preview)
    print(f"  Preview saved")

  Found 8 border lines
  Grid extent: y=200 to y=3414

page_054.png
  All lines at: [200, 657, 1116, 1576, 2028, 2486, 2949, 3414]
  Using grid: 200 → 3414
  Preview saved
  Found 4 border lines
  Grid extent: y=261 to y=1636

page_038.png
  All lines at: [261, 717, 1176, 1636]
  Using grid: 261 → 1636
  Preview saved
  Found 8 border lines
  Grid extent: y=219 to y=3440

page_080.png
  All lines at: [219, 676, 1136, 1597, 2050, 2509, 2974, 3440]
  Using grid: 219 → 3440
  Preview saved
  Found 8 border lines
  Grid extent: y=218 to y=3426

page_120.png
  All lines at: [218, 674, 1132, 1592, 2043, 2500, 2963, 3426]
  Using grid: 218 → 3426
  Preview saved


In [57]:
def detect_grid_lines(gray, min_line_length_ratio=0.3):
    """
    Use Hough line detection to find the actual printed grid lines.
    Returns sorted lists of x positions (vertical lines) and 
    y positions (horizontal lines).
    """
    h, w = gray.shape

    # Edge detection first
    edges = cv2.Canny(gray, 50, 150, apertureSize=3)

    # Detect lines
    lines = cv2.HoughLinesP(
        edges,
        rho=1,
        theta=np.pi/180,
        threshold=100,
        minLineLength=int(min(w, h) * min_line_length_ratio),
        maxLineGap=20
    )

    if lines is None:
        print("  No lines detected — falling back to margin estimates")
        return None, None

    h_lines = []  # horizontal — these give row boundaries
    v_lines = []  # vertical   — these give col boundaries

    for line in lines:
        x1, y1, x2, y2 = line[0]
        angle = abs(np.degrees(np.arctan2(y2 - y1, x2 - x1)))

        # Near-horizontal lines (within 5 degrees)
        if angle < 5 or angle > 175:
            y_mid = (y1 + y2) // 2
            h_lines.append(y_mid)

        # Near-vertical lines (within 5 degrees of 90)
        elif 85 < angle < 95:
            x_mid = (x1 + x2) // 2
            v_lines.append(x_mid)

    # Cluster nearby lines — many detections per physical line
    def cluster(positions, gap=20):
        if not positions:
            return []
        positions = sorted(positions)
        clusters = [[positions[0]]]
        for p in positions[1:]:
            if p - clusters[-1][-1] < gap:
                clusters[-1].append(p)
            else:
                clusters.append([p])
        return [int(np.mean(c)) for c in clusters]

    h_clustered = cluster(h_lines)
    v_clustered = cluster(v_lines)

    print(f"  Detected {len(h_clustered)} horizontal lines: {h_clustered}")
    print(f"  Detected {len(v_clustered)} vertical lines:   {v_clustered}")

    return h_clustered, v_clustered


def get_cell_boundaries_auto(img):
    """
    Build cell list directly from detected grid lines.
    Falls back to margin-based approach if detection fails.
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    h, w = img.shape[:2]

    h_lines, v_lines = detect_grid_lines(gray)

    # Need at least 2 of each to form cells
    if not h_lines or not v_lines or len(h_lines) < 2 or len(v_lines) < 2:
        print("  Falling back to fixed margins")
        return get_cell_boundaries(img)  # your margin-based fallback

    cells = []
    for row_idx in range(len(h_lines) - 1):
        for col_idx in range(len(v_lines) - 1):
            x1 = v_lines[col_idx]
            y1 = h_lines[row_idx]
            x2 = v_lines[col_idx + 1]
            y2 = h_lines[row_idx + 1]
            cells.append((x1, y1, x2, y2, row_idx, col_idx))

    print(f"  Built {len(cells)} cells from detected lines")
    return cells

In [65]:
def get_cell_boundaries(img, cols=6, rows=7, left_margin=70, right_margin=80):
    """Margin-based fallback if line detection fails."""
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    h, w = img.shape[:2]

    grid_top, grid_bottom = find_grid_extent(gray)

    usable_w = w - left_margin - right_margin
    usable_h = grid_bottom - grid_top
    cell_w   = usable_w // cols
    cell_h   = usable_h // rows

    cells = []
    for row in range(rows):
        for col in range(cols):
            x1 = left_margin + col * cell_w
            y1 = grid_top    + row * cell_h
            x2 = x1 + cell_w
            y2 = y1 + cell_h
            cells.append((x1, y1, x2, y2, row, col))

    return cells

In [66]:
test_pages = ["page_035.png", "page_036.png", "page_037.png", "page_038.png"]

for page in test_pages:
    img = cv2.imread(f"sourcebook/pages/{page}")
    if img is None:
        print(f"{page} — not found")
        continue

    cells = get_cell_boundaries_hybrid(img)
    preview = img.copy()

    for (x1, y1, x2, y2, row, col) in cells:
        h_cell = y2 - y1
        split_y = y1 + int(h_cell * 0.78)
        cv2.rectangle(preview, (x1, y1), (x2, y2), (0, 180, 90), 2)
        cv2.line(preview, (x1, split_y), (x2, split_y), (0, 140, 255), 2)

    out = f"sourcebook/dataset/{page.replace('.png','')}_hybrid_preview.png"
    cv2.imwrite(out, preview)
    print(f"Saved: {out}\n")

  Detected 7 horizontal lines: [210, 1129, 1582, 2036, 2492, 2795, 2953]
  Detected 4 vertical lines:   [983, 1416, 1853, 2289]
  Rows from 6 detected horizontal lines
  Cols evenly divided: 6
Saved: sourcebook/dataset/page_035_hybrid_preview.png

  Detected 4 horizontal lines: [1141, 1602, 2507, 3429]
  Detected 1 vertical lines:   [1358]
  Rows from 3 detected horizontal lines
  Cols evenly divided: 6
Saved: sourcebook/dataset/page_036_hybrid_preview.png

  Detected 5 horizontal lines: [707, 1161, 2074, 2534, 2884]
  Detected 2 vertical lines:   [545, 987]
  Rows from 4 detected horizontal lines
  Cols evenly divided: 6
Saved: sourcebook/dataset/page_037_hybrid_preview.png

  Detected 1 horizontal lines: [1184]
  Detected 1 vertical lines:   [2673]
  Horizontal line detection failed — using fallback
  Found 4 border lines
  Grid extent: y=261 to y=1636
  Rows from 1 detected horizontal lines
  Cols evenly divided: 6
Saved: sourcebook/dataset/page_038_hybrid_preview.png

